# Generated by Django 3.2.13 on 2022-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_release_date_movie_released_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='vote_average',
            new_name='vote_avg',
        ),
    ]
