# Generated by Django 3.2.13 on 2022-11-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_vote_average_movie_vote_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestmovie',
            name='best_of_best',
            field=models.BooleanField(default=False),
        ),
    ]
