# Generated by Django 3.2.13 on 2022-11-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_bestmovie_best_of_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
