# Generated by Django 3.2.13 on 2022-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20221117_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=100),
        ),
    ]
