# Generated by Django 3.2.13 on 2022-11-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='to_watch_movies',
            field=models.ManyToManyField(related_name='to_watch_user', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(related_name='watched_user', to='movies.Movie'),
        ),
    ]
