# Generated by Django 3.2.13 on 2022-11-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_messsage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='messsage',
            new_name='message',
        ),
    ]
